## How to use the UniRep mLSTM "babbler". This version demonstrates the 64-unit architecture which will be amenable to use on a personal laptop. For the 1900-unit production version see unirep_tutorial.ipynb

First, install the environment with your preferred method. We have tested the .yml conda load method on a conda python installation in Ubuntu 15.04, but not the others. We used pip to dump to requirements.txt which should be compatible with virtual env if you use python 3.6. 

To install something probably close enough to this environment you can use conda as follows:
```
conda create -n unirep python=3.6.0 tensorflow=1.3.0 jupyter pandas
source activate unirep
```

The most important version requirement is **tensorflow 1.3.0**. The others are likely fungible.

In [1]:
!aws s3 sync --no-sign-request --quiet s3://unirep-public/64_weights/ 64_weights/

In [2]:
import os
import tensorflow as tf
import numpy as np
from unirep import babbler64
tf.set_random_seed(42)
np.random.seed(42)

In [3]:
# Initialize the babbler. You need to provide the batch size you will use and the path to the weight directory.
batch_size = 12
b = babbler64(batch_size=batch_size, model_path="./64_weights")

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


The babbler needs to receive data in the correct format, a (batch_size, max_seq_len) matrix with integer values, where the integers correspond to an amino acid label at that position, and the end of the sequence is padded with 0s until the max sequence length to form a non-ragged rectangular matrix. We provide a formatting function to translate a string of amino acids into a list of integers with the correct codex:

In [4]:
seq = "MRKGEELFTGVVPILVELDGDVNGHKFSVRGEGEGDATNGKLTLKFICTTGKLPVPWPTLVTTLTYGVQCFARYPDHMKQHDFFKSAMPEGYVQERTISFKDDGTYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNFNSHNVYITADKQKNGIKANFKIRHNVEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSVLSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"

In [5]:
np.array(b.format_seq(seq))

array([24,  1,  2,  4, 13,  6,  6, 21, 18,  8, 13, 16, 16, 14, 17, 21, 16,
        6, 21,  5, 13,  5, 16,  9, 13,  3,  4, 18,  7, 16,  2, 13,  6, 13,
        6, 13,  5, 15,  8,  9, 13,  4, 21,  8, 21,  4, 18, 17, 11,  8,  8,
       13,  4, 21, 14, 16, 14, 20, 14,  8, 21, 16,  8,  8, 21,  8, 19, 13,
       16, 10, 11, 18, 15,  2, 19, 14,  5,  3,  1,  4, 10,  3,  5, 18, 18,
        4,  7, 15,  1, 14,  6, 13, 19, 16, 10,  6,  2,  8, 17,  7, 18,  4,
        5,  5, 13,  8, 19,  4,  8,  2, 15,  6, 16,  4, 18,  6, 13,  5,  8,
       21, 16,  9,  2, 17,  6, 21,  4, 13, 17,  5, 18,  4,  6,  5, 13,  9,
       17, 21, 13,  3,  4, 21,  6, 19,  9, 18,  9,  7,  3,  9, 16, 19, 17,
        8, 15,  5,  4, 10,  4,  9, 13, 17,  4, 15,  9, 18,  4, 17,  2,  3,
        9, 16,  6,  5, 13,  7, 16, 10, 21, 15,  5,  3, 19, 10, 10,  9,  8,
       14, 17, 13,  5, 13, 14, 16, 21, 21, 14,  5,  9,  3, 19, 21,  7,  8,
       10,  7, 16, 21,  7,  4,  5, 14,  9,  6,  4,  2,  5,  3,  1, 16, 21,
       21,  6, 18, 16,  8

I also provide a function that will check your Amino Acid sequences don't contain any characters which will break the babbler.

In [6]:
b.is_valid_seq(seq)

True

If you are into it, you could do your own data flow as long as you ensure that the data format is obeyed. Alternatively, you could use the data flow we implemented for babbler training, which happens in the tensorflow graph. It reads from a file of integer sequences, shuffles them around, collects them into groups of similar length (to minimize padding waste) and pads them to the max_length. We'll show you how to do that below:

In [7]:
# Before you can train your model, sequences need to be saved in the correct format
# suppose we have a new-line seperated file of AA sequences, seqs.txt, and we want to format them.
with open("seqs.txt", "r") as source:
    with open("formatted.txt", "w") as destination:
        for i,seq in enumerate(source):
            seq = seq.strip()
            if b.is_valid_seq(seq):
                formatted = ",".join(map(str,b.format_seq(seq)))
                destination.write(formatted)
                destination.write('\n')
            else:
                raise ValueError("Sequence {0} is not a valid sequence.".format(i))


In [8]:
# This is what the integer format looks like
!head -n1 formatted.txt

24,1,2,4,13,6,6,21,18,8,13,16,16,14,17,21,16,6,21,5,13,5,16,9,13,3,4,18,7,16,2,13,6,13,6,13,5,15,8,9,13,4,21,8,21,4,18,17,11,8,8,13,4,21,14,16,14,20,14,8,21,16,8,8,21,8,19,13,16,10,11,18,15,2,19,14,5,3,1,4,10,3,5,18,18,4,7,15,1,14,6,13,19,16,10,6,2,8,17,7,18,4,5,5,13,8,19,4,8,2,15,6,16,4,18,6,13,5,8,21,16,9,2,17,6,21,4,13,17,5,18,4,6,5,13,9,17,21,13,3,4,21,6,19,9,18,9,7,3,9,16,19,17,8,15,5,4,10,4,9,13,17,4,15,9,18,4,17,2,3,9,16,6,5,13,7,16,10,21,15,5,3,19,10,10,9,8,14,17,13,5,13,14,16,21,21,14,5,9,3,19,21,7,8,10,7,16,21,7,4,5,14,9,6,4,2,5,3,1,16,21,21,6,18,16,8,15,15,13,17,8,3,13,1,5,6,21,19,4


Notice that by default format_seq does not include the stop symbol (25) at the end of the sequence. This is the correct behavior if you are trying to train a top model, but not if you are training a babbler.

Now we can use my custom function to bucket, batch and pad sequences  from formatted.txt (which has the correct integer codex after calling)
babbler.format_seq(). The bucketing occurs in the graph. 

What is bucketing? Specify a lower and upper bound, and interval. All sequences less than lower or greater than upper will be batched together. Interval defines the "sides" of buckets between these bounds. Don't pick a small interval for a small dataset because
the function will just repeat a sequence if there are not enough to
fill a batch. All batches are the size you passed when initializing the babbler.
What else is this doing? 
- Shuffling the sequences by randomly sampling from a 10000 sequence buffer
- Automatically padding the sequences with zeros so the returned batch is a perfect rectangle
- Automatically repeating the dataset (you will need synthetic epochs)

In [9]:
bucket_op = b.bucket_batch_pad("formatted.txt", interval=1000) # Large interval

Inconveniently, this does not make it easy for a value to be associated with each sequence and not lost during shuffling. You can get around this by just prepending every integer sequence with the sequence label (eg, every sequence would be saved to the file as "{brightness value}, 24, 1, 5,..." and then you could just index out the first column after calling the bucket_op. Please reach out if you have questions on how to do this.

In [10]:
# Now that we have the bucket_op, we can simply sess.run() it to get
# a correctly formatted batch

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    batch = sess.run(bucket_op)
    
print(batch)
print(batch.shape)

[[24  1  7 ...  0  0  0]
 [24  1 15 ...  0  0  0]
 [24  1 15 ...  0  0  0]
 ...
 [24 16  4 ...  0  0  0]
 [24  1 15 ...  0  0  0]
 [24  1 16 ... 15 15  3]]
(12, 905)


You can look back and see that the batch_size we passed to __init__ is indeed 12, and the second dimension must be the longest sequence included in this batch. Now we have the data flow setup (note that as long as your batch looks like this, you don't need my flow), so we can proceed to implementing the graph. The module returns all the operations needed to feed in sequence and get out trainable representations.

In [11]:
final_hidden, x_placeholder, batch_size_placeholder, seq_length_placeholder, initial_state_placeholder = (
    b.get_rep_ops())

In [12]:
# final_hidden should be a batch_size x rep_dim matrix
# Lets say I want to train a basic feed-forward network as the top
# model, doing regression with MSE loss, Adam optimizer
y_placeholder = tf.placeholder(tf.float32, shape=[None,1], name="y")
initializer = tf.contrib.layers.xavier_initializer(uniform=False)

with tf.variable_scope("top"):
    prediction = tf.contrib.layers.fully_connected(
        final_hidden, 1, activation_fn=None, 
        weights_initializer=initializer,
        biases_initializer=tf.zeros_initializer()
    )

loss = tf.losses.mean_squared_error(y_placeholder, prediction)
    
# You can specifically train the top model first
learning_rate=.1
top_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope="top")
optimizer = tf.train.AdamOptimizer(learning_rate)
top_only_step_op = optimizer.minimize(loss, var_list=top_variables)
all_step_op = optimizer.minimize(loss)

In [13]:
# Notice that one of the placeholder is seq_length_placeholder.
# We need to compute the lengths of the sequences in each batch so
# that we can index out the the correct final hidden.
def nonpad_len(batch):
    nonzero = batch > 0
    lengths = np.sum(nonzero, axis=1)
    return lengths

nonpad_len(batch)

array([239, 342, 832, 445, 376, 376, 239, 232, 833, 361, 230, 905])

In [14]:
# toy example where we learn to predict 42 just training the top
y = [[42]]*batch_size
num_iters = 10
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_iters):
        batch = sess.run(bucket_op)
        length = nonpad_len(batch)
        loss_, __, = sess.run([loss, top_only_step_op],
                             feed_dict={
                                 x_placeholder: batch,
                                 y_placeholder: y,
                                 batch_size_placeholder: batch_size,
                                 seq_length_placeholder:length,
                                 initial_state_placeholder:b._zero_state
                             }
                             )
        print("Iteration {0}: {1}".format(i, loss_))

Iteration 0: 1734.759765625
Iteration 1: 1623.6226806640625
Iteration 2: 1511.0751953125
Iteration 3: 1416.2100830078125
Iteration 4: 1317.2991943359375
Iteration 5: 1211.9937744140625
Iteration 6: 1132.4569091796875
Iteration 7: 1045.625244140625
Iteration 8: 853.5608520507812
Iteration 9: 871.463623046875


In [15]:
# And another where we train the recurrent part as well
# This (64 dim) works on my laptop. I can save the trained weights 
# as long as I do it within the same session.
output_dir = "64_predict_42_weights"
os.makedirs(output_dir, exist_ok=True)

y = [[42]]*batch_size
num_iters = 5
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(num_iters):
        batch = sess.run(bucket_op)
        length = nonpad_len(batch)
        loss_, __, = sess.run([loss, all_step_op],
                             feed_dict={
                                 x_placeholder: batch,
                                 y_placeholder: y,
                                 batch_size_placeholder: batch_size,
                                 seq_length_placeholder:length,
                                 initial_state_placeholder:b._zero_state
                             }
                             )
        print("Iteration {0}: {1}".format(i, loss_))
    b.dump_weights(sess, dir_name=output_dir)

Iteration 0: 1734.759765625
Iteration 1: 1323.5887451171875
Iteration 2: 1130.878662109375
Iteration 3: 985.6826782226562
Iteration 4: 1764.68896484375
embed_matrix:0
[[ 0.5660815   0.8955147  -0.1885159   0.6356604  -0.6028085  -0.7326951
   0.20087385  0.21737194  0.47095132 -0.91131735]
 [-1.0232786   0.54812384 -0.72854435 -1.34639    -0.09061996 -0.02311213
   1.1732988  -0.4095448  -0.47606614  1.8321081 ]
 [ 0.45584428 -0.6069232   0.9532671   0.2915099   0.7765577   0.8228114
  -0.5294432  -0.726327   -1.6556437   1.2549229 ]
 [ 1.4317722   0.5739291   0.8102207   1.1333598   0.46475047 -1.1828618
  -0.59255713  0.49795157 -0.6493051  -0.11198798]
 [ 0.93484384  1.0777857   0.8630403  -0.39683938 -0.9239232   0.36277634
  -0.7250852  -0.40259346  0.86157525  1.3687888 ]
 [ 1.6488588  -0.44443074 -0.32334867 -0.30835348 -0.4490647   1.0848424
  -0.97556937 -1.000851   -0.510317   -0.20145565]
 [ 1.3636348   1.1649864   0.80961883  1.024184   -0.33165812  0.2480228
   0.01226537 

rnn/mlstm_stack/mlstm_stack2/mlstm_stack2/wx:0
[[-4.2452937e-01  5.8982499e-02 -2.3365217e-01 ...  1.5386789e-01
   4.6886805e-01  4.6942878e-01]
 [ 3.4952068e-01 -2.2036992e-03  2.8982225e-01 ...  4.0487744e-02
   2.5071386e-01  1.5408430e-01]
 [ 1.6143343e-01 -3.3745158e-01 -7.8739971e-02 ...  3.1169361e-01
  -2.4070670e-01 -8.7241545e-02]
 ...
 [ 8.2442924e-02 -1.1225529e-03 -1.6481963e-01 ...  2.8327471e-01
  -2.1822947e-01 -1.8905254e-01]
 [ 1.3562673e-01 -1.5305251e-01 -5.5751890e-01 ...  4.0857494e-04
   7.6714903e-03  5.8689639e-02]
 [ 1.6285323e-02 -7.7850282e-02  1.7386392e-01 ... -1.1249071e-01
  -4.0435952e-01 -2.5830230e-01]]
rnn/mlstm_stack/mlstm_stack2/mlstm_stack2/wh:0
[[ 0.03662869  0.27225006 -0.05581262 ... -0.36482158  0.04588121
   0.02988509]
 [-0.1433788   0.30308065 -0.12308303 ...  0.38968676  0.48483253
   0.4276707 ]
 [ 0.0032502   0.06529956  0.41688287 ...  0.10049125  0.35518557
   0.12896633]
 ...
 [-0.15129203 -0.1216966  -0.24334739 ... -0.16578382  0.1

top/fully_connected/biases:0
[0.49572054]
